version: '3.8'

services:
  agent-a:
    build: .
    container_name: agent-a-service
    ports:
      - "8001:8001"
    environment:
      - USE_MOCK_BEDROCK=true
      - LOG_LEVEL=INFO
      - HOST=0.0.0.0
      - PORT=8001
      - ROUTER_URL=http://router:5000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - agent-network

  # Router service (Vansh's service)
  router:
    image: nginx:alpine
    container_name: router-service
    ports:
      - "5000:5000"
    # This would be replaced with Vansh's actual Router service
    # For now, using nginx as placeholder
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge

volumes:
  logs:
    driver: local
